{% set name = "magic" %}
{% set version = "8.3.440" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RTimothyEdwards/magic/archive/refs/tags/{{ version }}.tar.gz
  sha256: e121b5273f8c1b1eff99c4a9c321c3d78668f7b42d283033d0f262b9c1e86d00

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - autoconf
    - automake
    - make
    - tcsh
    - python
    - {{ compiler('c') }}
  host:
    - tk
    - xorg-libx11
    - cairo
    - zlib
  run:
    # missing run_exports
    - xorg-libx11

test:
  commands:
    - magic -dnull -noconsole --version

about:
  home: http://opencircuitdesign.com/magic/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Magic VLSI Layout Tool
  description: |
    Magic is a venerable VLSI layout tool, written in the 1980's at Berkeley by John Ousterhout, now famous primarily for writing the scripting interpreter language Tcl.
    Due largely in part to its liberal Berkeley open-source license, magic has remained popular with universities and small companies.
    The open-source license has allowed VLSI engineers with a bent toward programming to implement clever ideas and help magic stay abreast of fabrication technology.
    However, it is the well thought-out core algorithms which lend to magic the greatest part of its popularity.
    Magic is widely cited as being the easiest tool to use for circuit layout, even for people who ultimately rely on commercial tools for their product design flow.
  doc_url: http://opencircuitdesign.com/magic/magic_docs.html
  dev_url: https://github.com/RTimothyEdwards/magic

extra:
  recipe-maintainers:
    - proppy
    - curtisma
